In [ ]:
import numpy as np

In [25]:
a = np.arange(12).reshape(3,4)
np.savetxt('a.txt',a,fmt='%.2e',header='hello',footer='python')

In [23]:
!cat a.txt

# hello
0.00e+00 1.00e+00 2.00e+00 3.00e+00
4.00e+00 5.00e+00 6.00e+00 7.00e+00
8.00e+00 9.00e+00 1.00e+01 1.10e+01
# python


In [27]:
b=np.loadtxt('a.txt')
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [28]:
c = np.loadtxt('a.txt',usecols=[1,2])
print(c)

[[ 1.  2.]
 [ 5.  6.]
 [ 9. 10.]]


In [30]:
d1,d2,d3,d4=np.loadtxt('a.txt',unpack=True)
print(d1)
print(d2)
print(d3)
print(d4)

[0. 4. 8.]
[1. 5. 9.]
[ 2.  6. 10.]
[ 3.  7. 11.]
