In [1]:
import numpy as np

In [15]:
from tempfile import TemporaryFile
outfile = TemporaryFile()

save()

In [5]:
save_x = np.arange(10)
np.save(outfile,save_x)
outfile.seek(0)
load_x = np.load(outfile)
print(load_x)

[0 1 2 3 4 5 6 7 8 9]


savez()未命名

In [10]:
savez_x = np.arange(10)
savez_y = np.sin(savez_x)
outfile.seek(0)
np.savez(outfile,savez_x,savez_y)
outfile.seek(0)
npzfile = np.load(outfile)
print(npzfile.files)
print(type(npzfile['arr_0']),npzfile['arr_0'])
print(type(npzfile['arr_1']),npzfile['arr_1'])
print(type(npzfile))

['arr_0', 'arr_1']
<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
<class 'numpy.lib.npyio.NpzFile'>


savez()命名

In [13]:
savez_x = np.arange(10)
savez_y = np.sin(savez_x)
outfile.seek(0)
np.savez(outfile,x=savez_x,y=savez_y)
outfile.seek(0)
npzfile = np.load(outfile)
print(npzfile.files)
print(type(npzfile['x']),npzfile['x'])
print(type(npzfile['y']),npzfile['y'])

['x', 'y']
<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


savez_compressed()

In [16]:
csave_x = np.random.rand(3,2)
csave_y = np.random.rand(4)
outfile.seek(0)
np.savez_compressed(outfile,x=csave_x,y=csave_y)
outfile.seek(0)
npcfile = np.load(outfile)
print(npcfile.files)
print(npcfile['x'])
print(npcfile['y'])

['x', 'y']
[[0.13725564 0.47769285]
 [0.41229551 0.57263086]
 [0.4192586  0.6394022 ]]
[0.03089119 0.50586187 0.82604336 0.73640738]


In [17]:
outfile.close()